version: '3.7'

services:
  exo-fast-api:
    container_name: exo-fast-api-cn
    build:
      context: ./
      dockerfile: ./DockerFile
    image: exo-fast-api:1.0
    hostname: exo-fast-api
    volumes:
      - ./app/:/code
      - ./app/config/log_conf.yml:/code/config/log_conf.yml
      - ./run_log/:/run_log
    ports:
      - '8080:8080'  
      #- '8043:8043'
    command: python ./main.py
